name: CCDC File Checks
author: CCDC
description: Check changed files for compliance
runs:
  using: "composite"
  steps:
    - run: python3 $GITHUB_ACTION_PATH/main.py ${{ github.event.head_commit.message }}
      shell: bash
branding:
  icon: 'check-square'
  color: 'green'
