name: CCDC File Checks
author: CCDC
description: Check changed files for compliance
runs:
  using: "composite"
  steps:
    - run: python3 $GITHUB_ACTION_PATH/main.py
      shell: bash
inputs:
  commitMessage:
    description: 'The commit message'
    required: true
branding:
  icon: 'check-square'
  color: 'green'
