#
# This code is Copyright (C) 2026 The Cambridge Crystallographic Data Centre
# (CCDC) of 12 Union Road, Cambridge CB2 1EZ, UK and a proprietary work of CCDC.
# This code may not be used, reproduced, translated, modified, disassembled or
# copied, except in accordance with a valid licence agreement with CCDC and may
# not be disclosed or redistributed in any form, either in whole or in part, to
# any third party. All copies of this code made in accordance with a valid
# licence agreement as referred to above must contain this copyright notice.
#
# No representations, warranties, or liabilities are expressed or implied in the
# supply of this code by CCDC, its servants or agents, except where such
# exclusion or limitation is prohibited, void or unenforceable under governing
# law.
#
name: CCDC File Checks
author: CCDC
description: Check changed files for compliance
inputs:
  commitMessage:
    description: 'The commit message'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install copywrite
      uses: hashicorp/setup-copywrite@v1.1.3

    - name: Validate Header Compliance
      run: copywrite headers --config "$GITHUB_ACTION_PATH/main/copywrite/.copywrite.hcl" --plan
      shell: bash

    - name: Run file compliance check
      run: python3 $GITHUB_ACTION_PATH/main.py
      shell: bash
      env:
        INPUT_COMMITMESSAGE: ${{ inputs.commitMessage }}
branding:
  icon: 'check-square'
  color: 'green'