#!/usr/bin/env python3
'''
This is a git hook migrated from hg.

Reference:
https://confluence.ccdc.cam.ac.uk/pages/viewpage.action?spaceKey=GIT&title=Hooks

'''

#import os
#import sys
#sys.path.append(os.path.dirname(os.path.abspath(__file__)))

import githooks

if __name__ == '__main__':
    exit(githooks.commit_hook())
