#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

case "$OSTYPE" in
  darwin*)
    $SCRIPT_DIR/Ccdc.CommitHooks.CommitHookExe --client-side --pre-merge-commit
  ;; 
  linux*)
    $SCRIPT_DIR/Ccdc.CommitHooks.CommitHookExe --client-side --pre-merge-commit
  ;; 
  msys*)
    $SCRIPT_DIR/Ccdc.CommitHooks.CommitHookExe.exe --client-side --pre-merge-commit
  ;; 
  *)
  echo "unsupported OSTYPE: $OSTYPE" ;;
esac
