#!/usr/bin/env bash
me=`basename "$0"`

case "$OSTYPE" in
  msys)
    echo "Running ${me} in MinGW"
    PYTHON_EXECUTABLE=python
  ;;
  *)
    echo "Running ${me} linux / mac / unix"
    if command -v python > /dev/null 2>&1; then
      PYTHON_EXECUTABLE=python
    else
      PYTHON_EXECUTABLE=python
    fi
esac

${PYTHON_EXECUTABLE} "${BASH_SOURCE[0]%.*}.py" "$@"
