# Standard CCDC pre-commit configuration
# Distribute this file to repositories to enable automatic copyright header formatting
repos:
  - repo: https://github.com/ccdc-opensource/commit-hooks
    rev: v8
    hooks:
      # Recommended: Automatically inserts or updates CCDC copyright headers on commit
      - id: copywrite-fix

      # Alternative: Validates compliance without modifying files (e.g. for local lint checks)
      # - id: copywrite-check
